extraction:
  cpp:
    prepare:
      packages:
        - pkg-config
        - qt5-default
        - qt5-qmake
        - qtdeclarative5-dev
        - qttools5-dev-tools
    index:
      build_command:
        - git submodule update --init
        - lrelease ./Qv2ray.pro
        - mkdir build && cd ./build
        - qmake ../
        - make
        
